org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configurationcache=false

# Fabric Properties
minecraft_version=26.3
supported_minecraft_versions=26.1,26.1.1,26.1.2,26.2,26.3
loader_version=0.19.5
loom_version=1.18.2

# Mod Properties
mod_version=1.0.3
maven_group=com.si6gma

# Dependencies
fabric_api_version=0.161.0+26.3

# Modrinth
modrinth_project_id=ESOV1nxn
